_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  OUTPUT_DIM: 13

SKILLS:
  - NAME: M1 - Trauma Assessment
    STEPS:
      - Optionally unclothe depending on situation.
      - Sweep* left leg.
      - Sweep* right leg.
      - Sweep* left arm.
      - Sweep* right arm.
      - Look Listen Feel Breathing.
      - Rake** chest.
      - Roll over casualty.
      - Rake the back and buttocks.
      - Check pulse.
      - Check skin temperature/quality.
      - Expose and look at chest.
      - Optionally reclothe depending on situation.
