CHECKPOINT: wandb/run-20240417_160138-ioy4g76e/files/best_model.pth
DATASET:
  BATCH_SIZE: 1
  DIR: /vast/irr2020/BBN
  NMACHINESTATES: 3
  NSTEPS: 20
  NWORKERS: 0
MODEL:
  GRU_DROPOUT: 0.5
  GRU_INPUT_SIZE: 1024
  GRU_NUM_LAYERS: 2
  VID_BACKBONE: omnivore_swinB_epic
  VID_EMBED_SIZE: 1024
  VID_NFRAMES: 32
  VID_MEAN: [0.485, 0.456, 0.406]
  VID_STD: [0.229, 0.224, 0.225]

  USE_STATE_HEAD: true
  SKILL_ID: ['M2', 'M3', 'M5', 'R18']
  SKILL_STEPS:
    M2: [11,13,2,16,6,12,15,7,19]
    M3: [1,8,0,18,15,19]
    M5: [8,4,5,14,1,19]
    R18: [3,8,17,9,10,19]
TRAIN:
  EPOCHS: 50
  LR: 0.001